MODUSERS - 306 POST and PUT of user object fail with error "Invalid Text format" if the object contains a non-required customFields of type text and the value is an empty string
folio-org/mod-users pull request #240
Opened 2022-03-31 05:35 UTC by DieHardJava

### Purpose 
POST and PUT of user object fail with error "Invalid Text format" if the object contains a non-required customFields of type text and the value is an empty string

### Approach
- added method removeCustomFieldIfEmpty which removes customfield if object value is empty before validation in postUsers and putUsersById methods
- wrote unit test for removeCustomFieldIfEmpty to check

2022-03-31 09:07 UTC, psmagin requested changes

2022-03-31 09:07 UTC, psmagin commented on src/main/java/org/folio/rest/impl/UsersAPI.java
> +  void removeCustomFieldIfEmpty(User entity) {
Make it private

2022-03-31 09:07 UTC, psmagin commented on src/main/java/org/folio/rest/impl/UsersAPI.java
> +      customField.entrySet().removeIf(obj -> obj.getValue().toString().isEmpty());
add check for `value instaceof String`

2022-03-31 09:07 UTC, psmagin commented on src/test/java/org/folio/rest/impl/UsersAPITest.java
> +
It should be an API test. Please, check how API tests are written in other test cases.

2022-03-31 11:54 UTC, psmagin approved these changes

2022-04-01 08:08 UTC, Igor-Gorchakov approved these changes

2022-04-01 08:09 UTC, Shans-Kaluhin approved these changes

2022-04-01 08:17 UTC, merged